---
# Playbook that runs tasks common across all servers

- include: apt_upgrade.yml
  tags:
    - dependency

- include: utils.yml
  tags:
    - dependency

- include: set_hostname.yml

# moved into individual roles
#- include: sync_source.yml
#  tags:
#    - sync
#    - web-api
#    - web-static
#    - web-both
#    - shell-api
#    - deploy-one
#    - deploy-section
#    - deploy-all
#    - redeploy-one
#    - redeploy-all
#    - redeploy-section

- include: util_admin_ssh_keys.yml
  tags:
    - never
    - update_admin_keys
