---
# Basic user tasks for all machines

# No password
- name: Ensure user exists with ssh key ({{ ansible_user }})
  user:
    name: "{{ ansible_user }}"
    shell: /bin/bash
    generate_ssh_key: yes

- name: Set up authorized keys
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ item }}"
  with_file: "{{keys}}"

- name: Fetch newly created ssh key
  fetch:
    src: "/home/{{ ansible_user }}/.ssh/id_rsa.pub"
    dest: "fetched/keys/{{ inventory_hostname }}_id_rsa.pub"
    flat: yes

- name: Add user to sudoers (no password)
  lineinfile:
    dest: /etc/sudoers
    regexp: "{{ ansible_user }} ALL"
    line: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
    state: present

# ensure other admin keys added to the user
- include: util_admin_ssh_keys.yml
