---
# Task list to add a user to the web site

- name: "Run add-web-user.py to create user ({{ web_user }})"
  shell:
    cmd: >
      . {{virtualenv_dir}}/bin/activate;
      {{scripts_dir}}/add-web-user.py
      -u '{{ web_user }}' -p '{{ web_pw }}' -e '{{ web_email }}' -f '{{web_admin_first}}' -l '{{web_admin_last}}'
  register: result
  changed_when: '"WARN" not in result.stderr'
